import Head from 'next/head';
import "../../public/assets/css/plugins/fontawesome-6.css";
import "../../public/assets/css/plugins/swiper.min.css";
import "../../public/assets/css/vendor/magnific-popup.css";
import "../../public/assets/css/vendor/bootstrap.min.css";
import "../../public/assets/css/vendor/metismenu.css";
import "../../public/assets/css/style.css";
import "../component/header/css/HeaderTwo.css";
import 'react-modal-video/css/modal-video.min.css';
import 'aos/dist/aos.css';
import Script from 'next/script';


export const metadata = {
  title: "Epacio Arquitectónico NextJs Template",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/icon.svg", // Ensure the path is correct
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Espacio Arquitectónico</title>
        <meta name="author" content="themewant" />
        <meta name="description" content="Espacio Arquitectónico NextJs Template" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/assets/images/icon.svg" />
      </Head>
      <body className='index-one'>

        <div class="cursor-dot" data-cursor-dot></div>
        <div class="cursor-outline" data-cursor-outline></div>
        {children}

        <Script
          src="/assets/js/plugins/smoothscroll.js"
          strategy="afterInteractive"
        />
      </body>
    </html>
  );
}
